[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from   = "/clean-prompt"
  to     = "/.netlify/functions/clean-prompt"
  status = 200

[[redirects]]
  from   = "/generate-image"
  to     = "/.netlify/functions/generate-image"
  status = 200

[[redirects]]
  from   = "/upscale-image"
  to     = "/.netlify/functions/upscale-image"
  status = 200

[[redirects]]
  from   = "/health"
  to     = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from   = "/create-checkout-session"
  to     = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]]
  from   = "/success"
  to     = "/.netlify/functions/order-success"
  status = 200

[[redirects]]
  from   = "/logo-studio"
  to     = "/logo-studio/index.html"
  status = 200
